### ISSUE TITLE
Add Faculty Data

### ISSUE THREAD

**Issue by AmanGxpta** [Velocity-IIITDWD/College-Website#1]
Go to https://iiitdwd.herokuapp.com/admin
username: velocity
password: velocity
You need to add faculty data from the official site.

<img width="1436" alt="Screenshot 2022-11-12 at 2 49 52 PM" src="https://user-images.githubusercontent.com/82807218/201467615-c1affc66-893a-421f-a23c-71908f7c062b.png">

see the result on 
https://iiitdwd.herokuapp.com/faculty

**Comment by kvishal2706** [comment]
Please assign this issue to me
